gestor/urls.py
from django.urls import path, include

from . import routers
from . import views

from django.contrib.auth import views as auth_views

app_name = 'gestor'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='gestor/base.html'), name='logout'),
]


urlpatterns += [
    path('empresa/', views.EmpresaCreate.as_view(), name='create_empresa'),
    path('empresa/<slug:rfc>/', views.EmpresaContactoList.as_view(), name='detail_empresa'),
    path('empresa/<slug:rfc>/actualizar/', views.EmpresaUpdate.as_view(), name='update_empresa'),
    path('empresa/<slug:rfc>/eliminar/', views.EmpresaDelete.as_view(), name='delete_empresa'),
    path('empresas/', views.EmpresaList.as_view(), name='list_empresa'),
]

urlpatterns += [
    path('contactos/', views.ContactoList.as_view(), name='list_contacto'),
    path('empresa/<slug:rfc>/contactos/', views.EmpresaContactoList.as_view(), name='list_contacto_empresa'),
    path('empresa/<slug:rfc>/contacto/', views.ContactoCreate.as_view(), name='create_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/', views.ContactoDetail.as_view(), name='detail_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/actualizar/', views.ContactoUpdate.as_view(), name='update_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/eliminar/', views.ContactoDelete.as_view(), name='delete_contacto'),
]

urlpatterns += [
    path('productos/', views.ProductoList.as_view(), name='list_producto'),
    path('producto/', views.ProductoCreate.as_view(), name='create_producto'),
    path('producto/<int:id>/', views.ProductoUpdate.as_view(), name='detail_producto'),
    path('producto/<int:id>/actualizar/', views.ProductoUpdate.as_view(), name='update_producto'),
    path('producto/<int:id>/eliminar/', views.ProductoDelete.as_view(), name='delete_producto'),
]

urlpatterns += [
    path('cotizaciones/', views.CotizacionList.as_view(), name='list_cotizacion'),
    path('empresa/<slug:rfc>/cotizaciones/', views.EmpresaCotizacionList.as_view(), name='list_cotizacion_empresa'),
    path('empresa/<slug:rfc>/cotizacion/', views.CotizacionCreate.as_view(), name='create_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/', views.CotizacionDetail.as_view(), name='detail_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/', views.CotizacionGeneratePDF.as_view(), name='generate_pdf_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/actualizar/', views.CotizacionUpdate.as_view(), name='update_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/eliminar/', views.ProductoCotizadoDelete.as_view(), name='delete_prodcuto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/actualizar/', views.ProductoCotizadoUpdate.as_view(), name='update_producto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto/<int:id>/agregar/', views.ProductoAdd.as_view(), name='add_producto'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/facturas/', views.EmpresaFacturaList.as_view(), name='list_factura_empresa'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/facturar/', views.FacturaCreate.as_view(), name='create_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/', views.FacturaDetail.as_view(), name='detail_factura'),
]

urlpatterns += [
    path('api/', include(routers.router.urls)),
]

revolucion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestor/', include('gestor.urls')),
]

gestor/models.py
from django.db import models

from django.contrib.auth.models import User

from .utils import update_producto_cotizado, update_cotizacion

# Dictionaries
class CatalogoClaveProducto(models.Model):
    clave = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        return '%d' % (self.clave)

#Datos Escenciales para el funcionamiento

class Empresa(models.Model):
    rfc = models.CharField(
        max_length=13,
        primary_key=True,
    )
    razon_social = models.CharField(max_length=40)
    correo = models.EmailField(max_length=40)
    telefono = models.CharField(max_length=22)
    BANCOS = (
        (1, 'Bancomer'),
        (2, 'Banamex'),
        (3, 'Banorte'),
        (3, 'IXE'),
        (0, 'N/A'),
    )
    banco = models.IntegerField(
        choices=BANCOS,
        default=0,
    )
    referencia_bancaria = models.IntegerField(default = -1)
    CUIDAD_ESTADO = (
        (1, 'CDMX/CDMX'),
        (2, 'Estado de México/Toluca'),
    )
    FORMAS_PAGO = (
        (0, 'Efectivo'),
        (1, 'Cheque nominativo'),
        (2, 'Transferencia electrónicade fondos'),
        (3, 'Por definir'),
    )
    forma_pago = models.IntegerField(
        choices=FORMAS_PAGO,
        default=0,
    )
    METODOS_PAGO = (
        (0, 'PUE'),
        (1, 'PPD'),
    )
    metodo_pago = models.IntegerField(
        choices=METODOS_PAGO,
        default=0,
    )
    TIPOS_COMPROBANTE = (
        (0, 'I'),
        (1, 'E'),
        (2, 'T'),
        (3, 'P'),
        (4, 'N'),
    )
    tipo_comprobante = models.IntegerField(
        choices=TIPOS_COMPROBANTE,
        default=0,
    )
    cuidad_estado = models.IntegerField(
        choices=CUIDAD_ESTADO,
        default=1,
    )
    cp = models.IntegerField(default=-1)
    direccion = models.CharField(
        max_length=20,
        blank=True, 
        null=True,
    )

    def __str__(self):
        return '%s' % self.rfc

class Contacto(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=23)
    correo = models.EmailField(max_length=20)
    numero = models.CharField(max_length=20)
    PREFIJO_CHOICES = (
        (0, ''),
        (1, 'Sr.'),
        (2, 'Sra.'),
        (3, 'Lic.'),
        (4, 'Ing.'),
    )
    prefijo = models.IntegerField(
        choices=PREFIJO_CHOICES,
        default=0,
    )

    def __str__(self):
        return '%d[Nombre:%s]' % (self.id, self.nombre)

class Producto(models.Model):
    numero_parte = models.CharField(max_length=40)
    TIPOS_PRODUCTO = (
        ('Prd', 'Producto'),
        ('Srv', 'Servicio'),
    )
    tipo_producto = models.CharField(
        max_length=3,
        choices=TIPOS_PRODUCTO,
        default='Prd',
    )
    UNIDADES_MEDIDA = (
        ('H87', 'Pieza'),
        ('XBX', 'Caja'),
        ('O', 'Otro'),
        ('0', 'No Aplica'),
    )
    unidad_medida = models.CharField(
        max_length=3,
        choices=UNIDADES_MEDIDA,
        default='H87',
    )
    clave = models.ForeignKey(
        CatalogoClaveProducto,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    ALIMENTO_IVA = 0
    SIN_ESPECIFICAR_IVA = 16
    TIPOS_IVA = (
        (ALIMENTO_IVA, 'ALIMENTO(0%)'),
        (SIN_ESPECIFICAR_IVA, 'S/A(16%)'),
    )
    tipo_iva = models.IntegerField(
        choices=TIPOS_IVA,
        default=SIN_ESPECIFICAR_IVA,
    )
    descripcion = models.TextField(
        max_length=100,
        blank=True,
    )


# Cotización

class Cotizacion(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.SET_NULL,
        blank=True, 
        null=True,
        related_name='cotizaciones',
    )
    usuario = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    referencia = models.CharField(
        max_length=20,
        blank=True, 
        null=True,
    )
    fecha = models.DateField(auto_now_add=True)
    contacto = models.ForeignKey(
        Contacto,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    costo_operacion = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    monto_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    subtotal = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    is_factura = models.BooleanField(default=False)

    def __str__(self):
        return '%d[Nombre:%s]' % (self.id,self.referencia)

    def save(self, *args, **kwargs):
        update_cotizacion(self)
        super(Cotizacion, self).save(*args, **kwargs)


# Cuando se cotize un producto, en costo debera de aparecer el costo del producto
# junto con el respectivo margen de ganancia
class ProductoCotizado(models.Model):
    cotizacion = models.ForeignKey(
        Cotizacion,
        on_delete=models.CASCADE,
        related_name='productos_cotizados',
    )
    producto = models.ForeignKey(
        Producto,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
    )
    provedor = models.ForeignKey(
        Empresa,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    precio = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    costo = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    margen_ganancia = models.PositiveIntegerField(default=0)
    cantidad = models.PositiveIntegerField(default=1)
    monto_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=-1.00,
    )
    importe = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    descripcion = models.TextField(
        max_length=55,
        blank=True,
    )

    def __str__(self):
        return '%d[Nombre:%s][Cotizacion:%d]' % (self.id, self.nombre, self.cotizacion.id)

    def save(self, *args, **kwargs):
        update_producto_cotizado(self)
        super(ProductoCotizado, self).save(*args, **kwargs)
        cotizacion = self.cotizacion
        update_cotizacion(cotizacion)
        cotizacion.save()

    def delete(self, *args, **kwargs):
        cotizacion = self.cotizacion
        super(ProductoCotizado, self).delete(*args, **kwargs)
        update_cotizacion(cotizacion)
        cotizacion.save()


class Factura(models.Model):
    cotizacion = models.OneToOneField(
        Cotizacion,
        on_delete=models.CASCADE,
        related_name='factura',
    )
    firma = models.CharField(max_length=30)
    monto_pagado = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    ESTADOS = (
        (-1, 'Cancelada'),
        (0, 'En curso'),
        (1, 'Pagada'),
    )
    estado = models.IntegerField(
        choices=ESTADOS,
        default=0,
    )
    fecha_pago = models.DateField(
        blank=True, 
        null=True,
    )

    def __str__(self):
        return '%d[Cotizacion:%d][Empresa:%s]' % (self.id, self.cotizacion.id, self.cotizacion.empresa.rfc)

class FacturaArchivos(models.Model):
    factura = models.ForeignKey(
        Factura,
        on_delete=models.CASCADE,
        related_name='factura_archivos',
    )
    ESTADOS_FACTURA = (
        (0, 'No pagada'),
        (1, 'Pagada'),
        (2, 'Cancelada'),
    )
    estado_factura = models.IntegerField(
        choices=ESTADOS_FACTURA,
        default=0,
    )

gestor/forms.py
from django.forms import ModelForm

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Empresa
from .models import Contacto
from .models import Producto
from .models import Cotizacion
from .models import ProductoCotizado
from .models import Factura

class EmpresaCreateForm(ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'
        labels = {
            'rfc': 'RFC',
            'cp': 'CP',
            'cuidad_estado': 'Cuidad/Estado',
            'direccion':  'Dirección',
            'forma_pago': 'Forma de pago',
            'metodo_pago': 'Método de pago',
            'tipo_comprobante': 'Tipo de comprobante',
            'razon_social': 'Razón social',
        }

class EmpresaUpdateForm(ModelForm):
    class Meta:
        model = Empresa
        exclude = ['rfc']
        labels = {
            'cp': 'CP',
            'cuidad_estado': 'Cuidad/Estado',
            'direccion':  'Dirección',
        }

class ContactoCreateForm(ModelForm):
    class Meta:
        model = Contacto
        exclude = ['empresa']

class CotizacionCreateForm(ModelForm):
    class Meta:
        model = Cotizacion
        fields = ['referencia', 'contacto', 'costo_operacion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['contacto'].empty_label = "(Contacto)"

class CotizacionUpdateForm(ModelForm):
    class Meta:
        model = Cotizacion
        fields = ['referencia', 'contacto', 'costo_operacion']
        labels = {
            'costo_operacion': 'Costo de operación',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['contacto'].empty_label = "(Contacto)"

class ProductoCotizadoUpdateForm(ModelForm):
    class Meta:
        model = ProductoCotizado
        fields = ['costo', 'cantidad', 'provedor', 'margen_ganancia', 'descripcion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['provedor'].empty_label = "(Provedor)"

class ProductoAddForm(ModelForm):
    class Meta:
        model = ProductoCotizado
        fields = ['costo', 'cantidad', 'provedor', 'margen_ganancia', 'descripcion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['provedor'].empty_label = "(Provedor)"

class FacturaCreateForm(ModelForm):
    class Meta:
        model = Factura
        fields = ['firma']

class FacturaUpdateForm(ModelForm):
    class Meta:
        model = Factura
        fields = ['monto_pagado']

class ProductoCreateForm(ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        labels = {
            'tipo_iva': 'Tipo de IVA',
            'tipo_producto': 'Tipo de producto',
            'unidad_medida': 'Unidad de medida',
            'descripcion': 'Descripción',
            'numero_parte': 'Numero de parte',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clave'].empty_label = "(Clave)"

class UserSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

templates/gestor/contacto/ContactoCreate.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}
{% load widget_tweaks %}
{{ object.empresa.rfc }}
<form method="post">{% csrf_token %}
  <div class="row">
    <div class="col">
      <label for="{{ form.prefijo.id_for_label }}">{{ form.prefijo.label_tag }}</label>
      {{ form.prefijo|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.nombre.id_for_label }}">{{ form.nombre.label_tag }}</label>
      {{ form.nombre|add_class:'form-control' }}
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label for="{{ form.correo.id_for_label }}">{{ form.correo.label_tag }}</label>
      {{ form.correo|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.numero.id_for_label }}">{{ form.numero.label_tag }}</label>
      {{ form.numero|add_class:'form-control' }}
    </div>
  </div>
  <input type="submit" class="btn btn-lg btn-secondary my-2" value="Registrar Contacto">
</form>
{% endblock %}

templates/gestor/contacto/ContactoDelete.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block  empresa_item_content %}
<form method="post"> {% csrf_token %}
  <h5>¿Estas seguro de eliminar el contacto {{ contacto.nombre }}?</h5>
  <input type="submit" class="btn btn-danger btn-lg my-2" value="Eliminar Contacto">
</form>
{% endblock %}

templates/gestor/contacto/ContactoDetail.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}
<h3>Contacto: <a href="{% url 'gestor:detail_contacto' empresa.rfc contacto.id %}">{{contacto.id}}</a></h3>
<h4>Nombre: {{contacto.nombre}}</h4>
<h5>correo: {{contacto.correo}}</h5>
<h6>Facturas: </h6>
<table class="table table-hover" style="width:100%">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Fecha</th>
        <th scope="col">Costo De Operación</th>
        <th scope="col">Monto IVA</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    {% for cotizacion in object_list %}
      <tr>
      {% if cotizacion.is_factura %}
        <th scope="col" class="table-success">
          <a href="{% url 'gestor:detail_cotizacion' empresa.rfc cotizacion.id %}">
            {{cotizacion.id}}
          </a>
        </th>
      {% else %}
        <th scope="col" class="table-danger">
          <a href="{% url 'gestor:detail_cotizacion' empresa.rfc cotizacion.id %}">
            {{cotizacion.id}}
          </a>
        </th>
      {% endif %}
        <th scope="col">{{cotizacion.fecha}}</th>
        <th scope="col">${{cotizacion.costo_de_operacion}}</th>
        <th scope="col">${{cotizacion.monto_iva}}</th>
        <th scope="col">${{cotizacion.total}}</th>
      </tr>
    {% endfor %}
  </table>

</div>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ i }} <span class="sr-only">actual</span></a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Siguiente</span>
        </a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Siguiente</span>
      </a>
    </li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

templates/gestor/contacto/ContactoList(Empresa).html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gestor:list_factura_empresa' empresa.rfc %}">Facturas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gestor:list_cotizacion_empresa' empresa.rfc %}">Cotizaciones</a>
  </li>
  <li class="nav-item">
  <li class="nav-item">
    <a class="nav-link active" href="#">Contactos</a>
  </li>
</ul>
<div class="my-2">
  <h5>
    Contactos:
    <a class="btn btn-secondary" role="button" href="{% url 'gestor:create_contacto' empresa.rfc %}">Registar Contacto</a>
  </h5>
</div>

<table class="table table-hover" style="width:100%">
    <thead class="thead-light">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Correo</th>
        <th scope="col">Número</th>
      </tr>
    </thead>
    {% for contacto in object_list %}
      <tr class="clickable-tr" href="{% url 'gestor:detail_contacto' empresa.rfc contacto.id %">
        <th scope="col">
          <div id="contactoAccordion{{contacto.id}}">

            <div class="card">
              <div class="car-header" id="headingThree">
                <h6 class="mb-0">
                  <button class="btn btn-link" data-toggle="collapse" data-target="#collapseContacto{{contacto.id}}"
                    aria-expanded="true" aria-controls="collapseContacto{{contacto.id}}">
                    {{ contacto.get_prefijo_display }} {{ contacto.nombre }}
                  </button>
                </h6>
              </div>
            </div>

            <div id="collapseContacto{{contacto.id}}" class="collapse not-show"
              aria-labelledby="headingThree" data-parent="contactoAccordion{{contacto.id}}">
              <div class="card-body">
                <h6>
                  <a class="btn btn-outline-warning mx-2" role="button"
                    href="{% url 'gestor:update_contacto' empresa.rfc contacto.id %}">
                    Actualizar
                  </a>
                  <a class="btn btn-outline-danger" role="button"
                    href="{% url 'gestor:delete_contacto' empresa.rfc contacto.id %}">
                    Eliminar
                  </a>
                </h6>
              </div>
            </div>

            <a href="#">

            </a>
          </div>
        </th>
        <th scope="col">
          {{ contacto.correo }}
        </th>
        <th scope="col">
          {{ contacto.numero }}
        </th>
      </tr>
    {% endfor %}
  </table>

</div>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ i }} <span class="sr-only">actual</span></a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Siguiente</span>
        </a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Siguiente</span>
      </a>
    </li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/gestor/contacto/ContactoList.html
{% extends "gestor/base.html" %}

{% block title %}
  Contactos
{% endblock %}

{% block actions %}
  <h2>Contactos</h2>
{% endblock %}

{% block  content %}

<div id="ContactoList">
  <h5 class="my-2">
    Buscar Contacto:
    <div class="form-inline my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="id, nombre, empresa"
        v-model="search_term" aria-label="Buscar">
      <button class="btn btn-outline-success my-sm-0"
        v-on:click.prevent="getContactoList()">Buscar</button>
    </div>
  </h5>
  <div >
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nombre</th>
          <th scope="col">Empresa</th>
        </tr>
        <tbody >
          <tr v-for="contacto in contactoList">
            <th scope="col">
              <a :href="getContactoUrl(contacto)">${contacto.id}</a>
            </th>
            <th scope="col">${contacto.nombre}</th>
            <th scope="col">
              <a :href="getContactoEmpresaUrl(contacto)">${contacto.empresa}</a>
            </th>
          </tr>
        </tbody>
      </thead>
    </table>
  </div>
</div>

{% endblock %}

{% block scripts %}
  {% load static %}
  <script src="{% static 'frontend/contacto_list.js' %}"></script>
{% endblock %}

templates/gestor/contacto/ContactoUpdate.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}
{% load widget_tweaks %}
<form method="post">{% csrf_token %}
  <div class="row">
    <div class="col">
      <label for="{{ form.prefijo.id_for_label }}">{{ form.prefijo.label_tag }}</label>
      {{ form.prefijo|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.nombre.id_for_label }}">{{ form.nombre.label_tag }}</label>
      {{ form.nombre|add_class:'form-control' }}
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label for="{{ form.correo.id_for_label }}">{{ form.correo.label_tag }}</label>
      {{ form.correo|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.numero.id_for_label }}">{{ form.numero.label_tag }}</label>
      {{ form.numero|add_class:'form-control' }}
    </div>
  </div>
  <input type="submit" class="btn btn-secondary my-2" value="Guardar Cambios">
</form>
{% endblock %}