gestor/urls.py
from django.urls import path, include

from . import routers
from . import views

from django.contrib.auth import views as auth_views

app_name = 'gestor'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='gestor/base.html'), name='logout'),
]


urlpatterns += [
    path('empresa/', views.EmpresaCreate.as_view(), name='create_empresa'),
    path('empresa/<slug:rfc>/', views.EmpresaContactoList.as_view(), name='detail_empresa'),
    path('empresa/<slug:rfc>/actualizar/', views.EmpresaUpdate.as_view(), name='update_empresa'),
    path('empresa/<slug:rfc>/eliminar/', views.EmpresaDelete.as_view(), name='delete_empresa'),
    path('empresas/', views.EmpresaList.as_view(), name='list_empresa'),
]

urlpatterns += [
    path('contactos/', views.ContactoList.as_view(), name='list_contacto'),
    path('empresa/<slug:rfc>/contactos/', views.EmpresaContactoList.as_view(), name='list_contacto_empresa'),
    path('empresa/<slug:rfc>/contacto/', views.ContactoCreate.as_view(), name='create_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/', views.ContactoDetail.as_view(), name='detail_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/actualizar/', views.ContactoUpdate.as_view(), name='update_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/eliminar/', views.ContactoDelete.as_view(), name='delete_contacto'),
]

urlpatterns += [
    path('productos/', views.ProductoList.as_view(), name='list_producto'),
    path('producto/', views.ProductoCreate.as_view(), name='create_producto'),
    path('producto/<int:id>/', views.ProductoUpdate.as_view(), name='detail_producto'),
    path('producto/<int:id>/actualizar/', views.ProductoUpdate.as_view(), name='update_producto'),
    path('producto/<int:id>/eliminar/', views.ProductoDelete.as_view(), name='delete_producto'),
]

urlpatterns += [
    path('cotizaciones/', views.CotizacionList.as_view(), name='list_cotizacion'),
    path('empresa/<slug:rfc>/cotizaciones/', views.EmpresaCotizacionList.as_view(), name='list_cotizacion_empresa'),
    path('empresa/<slug:rfc>/cotizacion/', views.CotizacionCreate.as_view(), name='create_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/', views.CotizacionDetail.as_view(), name='detail_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/', views.CotizacionGeneratePDF.as_view(), name='generate_pdf_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/actualizar/', views.CotizacionUpdate.as_view(), name='update_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/eliminar/', views.ProductoCotizadoDelete.as_view(), name='delete_prodcuto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/actualizar/', views.ProductoCotizadoUpdate.as_view(), name='update_producto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto/<int:id>/agregar/', views.ProductoAdd.as_view(), name='add_producto'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/facturas/', views.EmpresaFacturaList.as_view(), name='list_factura_empresa'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/facturar/', views.FacturaCreate.as_view(), name='create_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/', views.FacturaDetail.as_view(), name='detail_factura'),
]

urlpatterns += [
    path('api/', include(routers.router.urls)),
]

revolucion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestor/', include('gestor.urls')),
]

gestor/forms.py
from django.forms import ModelForm

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Empresa
from .models import Contacto
from .models import Producto
from .models import Cotizacion
from .models import ProductoCotizado
from .models import Factura

class EmpresaCreateForm(ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'
        labels = {
            'rfc': 'RFC',
            'cp': 'CP',
            'cuidad_estado': 'Cuidad/Estado',
            'direccion':  'Dirección',
            'forma_pago': 'Forma de pago',
            'metodo_pago': 'Método de pago',
            'tipo_comprobante': 'Tipo de comprobante',
            'razon_social': 'Razón social',
        }

class EmpresaUpdateForm(ModelForm):
    class Meta:
        model = Empresa
        exclude = ['rfc']
        labels = {
            'cp': 'CP',
            'cuidad_estado': 'Cuidad/Estado',
            'direccion':  'Dirección',
        }

class ContactoCreateForm(ModelForm):
    class Meta:
        model = Contacto
        exclude = ['empresa']

class CotizacionCreateForm(ModelForm):
    class Meta:
        model = Cotizacion
        fields = ['referencia', 'contacto', 'costo_operacion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['contacto'].empty_label = "(Contacto)"

class CotizacionUpdateForm(ModelForm):
    class Meta:
        model = Cotizacion
        fields = ['referencia', 'contacto', 'costo_operacion']
        labels = {
            'costo_operacion': 'Costo de operación',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['contacto'].empty_label = "(Contacto)"

class ProductoCotizadoUpdateForm(ModelForm):
    class Meta:
        model = ProductoCotizado
        fields = ['costo', 'cantidad', 'provedor', 'margen_ganancia', 'descripcion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['provedor'].empty_label = "(Provedor)"

class ProductoAddForm(ModelForm):
    class Meta:
        model = ProductoCotizado
        fields = ['costo', 'cantidad', 'provedor', 'margen_ganancia', 'descripcion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['provedor'].empty_label = "(Provedor)"

class FacturaCreateForm(ModelForm):
    class Meta:
        model = Factura
        fields = ['firma']

class FacturaUpdateForm(ModelForm):
    class Meta:
        model = Factura
        fields = ['monto_pagado']

class ProductoCreateForm(ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        labels = {
            'tipo_iva': 'Tipo de IVA',
            'tipo_producto': 'Tipo de producto',
            'unidad_medida': 'Unidad de medida',
            'descripcion': 'Descripción',
            'numero_parte': 'Numero de parte',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clave'].empty_label = "(Clave)"

class UserSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

gestor/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse
from django.template.loader import get_template
from django.http import HttpResponse

from django.views import View
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from .models import Empresa
from .forms import EmpresaCreateForm, EmpresaUpdateForm

from .models import Contacto
from .forms import ContactoCreateForm

from .models import Producto
from .forms import ProductoCreateForm

from .models import Cotizacion
from .forms import CotizacionCreateForm, CotizacionUpdateForm

from .models import ProductoCotizado
from .forms import ProductoAddForm, ProductoCotizadoUpdateForm

from .models import Factura
from .forms import FacturaCreateForm
from .utils import render_to_pdf

from .forms import UserSignUpForm

class HomeView(TemplateView):
    template_name = 'gestor/home.html'

class EmpresaList(TemplateView):
    template_name = 'gestor/empresa/EmpresaList.html'

class EmpresaCreate(CreateView):
    template_name = 'gestor/empresa/EmpresaCreate.html'
    model = Empresa
    form_class = EmpresaCreateForm

    def get_success_url(self, **kwargs):
        return reverse('gestor:detail_empresa', kwargs={'rfc': self.object.rfc })

class EmpresaUpdate(UpdateView):
    template_name = 'gestor/empresa/EmpresaUpdate.html'
    model = Empresa
    form_class = EmpresaUpdateForm
    context_object_name = 'empresa'
    pk_url_kwarg = 'rfc'

    def get_success_url(self, **kwargs):
        return reverse('gestor:detail_empresa', kwargs={'rfc': self.object.rfc})

class EmpresaDelete(DeleteView):
    template_name = 'gestor/empresa/EmpresaDelete.html'
    model = Empresa
    context_object_name = 'empresa'
    pk_url_kwarg = 'rfc'

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_empresa')

class ContactoList(TemplateView):
    template_name = 'gestor/contacto/ContactoList.html'

class EmpresaContactoList(SingleObjectMixin, ListView):
    template_name = 'gestor/contacto/ContactoList(Empresa).html'
    model = Empresa
    pk_url_kwarg='rfc'
    context_object_name = 'empresa'
    paginate_by = 25

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Empresa.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.contacto_set.all()

class ContactoCreate(CreateView):
    template_name = 'gestor/contacto/ContactoCreate.html'
    model = Contacto
    form_class = ContactoCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def form_valid(self, form):
        form.instance.empresa = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_contacto_empresa', kwargs={'rfc': self.kwargs['rfc']})

class ContactoDetail(SingleObjectMixin, ListView):
    template_name = 'gestor/contacto/ContactoDetail.html'
    model = Contacto
    pk_url_kwarg='id'
    context_object_name = 'contacto'
    paginate_by = 25

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Contacto.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_queryset(self):
        return self.object.cotizacion_set.all()

class ContactoUpdate(UpdateView):
    template_name='gestor/contacto/ContactoUpdate.html'
    model = Contacto
    form_class = ContactoCreateForm
    context_object_name = 'contacto'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_contacto_empresa',  kwargs={'rfc': self.kwargs['rfc']})

class ContactoDelete(DeleteView):
    template_name='gestor/contacto/ContactoDelete.html'
    model = Contacto
    context_object_name = 'contacto'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_contacto_empresa',  kwargs={'rfc': self.kwargs['rfc']})

# Cotización

class CotizacionList(TemplateView):
    template_name = 'gestor/cotizacion/CotizacionList.html'

class EmpresaCotizacionList(SingleObjectMixin, ListView):
    template_name = 'gestor/cotizacion/CotizacionList(Empresa).html'
    model = Empresa
    pk_url_kwarg='rfc'
    context_object_name = 'empresa'
    paginate_by = 25

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Empresa.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.cotizaciones.all()

class CotizacionCreate(CreateView):
    template_name = 'gestor/cotizacion/CotizacionCreate.html'
    form_class = CotizacionCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def form_valid(self, form):
        form.instance.empresa = Empresa.objects.get(rfc=self.kwargs['rfc'])
        form.instance.usuario = self.request.user
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        cotizacion_kwargs = {
            'rfc': self.kwargs['rfc'],
            'pk': self.object.pk,
        }
        return reverse('gestor:detail_cotizacion', kwargs=cotizacion_kwargs)


class CotizacionDetail(DetailView):
    template_name = 'gestor/cotizacion/CotizacionDetail.html'
    model = Cotizacion
    context_object_name = 'cotizacion'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        context['producto_cotizado_list'] = self.object.productos_cotizados.all()
        context['factura'] = None
        if self.object.is_factura:
            context['factura'] = self.object.factura
        return context

class CotizacionUpdate(UpdateView):
    template_name = 'gestor/cotizacion/CotizacionUpdate.html'
    model = Cotizacion
    form_class = CotizacionUpdateForm
    context_object_name = 'cotizacion'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_success_url(self, **kwargs):
        cotizacion_kwargs = {
            'rfc': self.kwargs['rfc'],
            'pk': self.object.pk,
        }
        return reverse('gestor:detail_cotizacion', kwargs=cotizacion_kwargs)

# Productos Cotizados

class ProductoCotizadoUpdate(UpdateView):
    template_name='gestor/producto/ProductoCotizadoUpdate.html'
    model = ProductoCotizado
    form_class = ProductoCotizadoUpdateForm
    context_object_name = 'producto_cotizado'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        context['cotizacion'] = Cotizacion.objects.get(pk=self.kwargs['pk'])
        context['producto'] = self.object.producto
        return context

    def get_success_url(self, **kwargs):
        cotizacion_kwargs = {
            'rfc': self.kwargs['rfc'],
            'pk': self.kwargs['pk'],
        }
        return reverse('gestor:detail_cotizacion', kwargs=cotizacion_kwargs)

class ProductoCotizadoDelete(DeleteView):
    template_name='gestor/producto/ProductoCotizadoDelete.html'
    model = ProductoCotizado
    context_object_name = 'producto_cotizado'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        context['cotizacion'] = Cotizacion.objects.get(pk=self.kwargs['pk'])
        return context

    def get_success_url(self, **kwargs):
        cotizacion_kwargs = {
            'rfc': self.kwargs['rfc'],
            'pk': self.kwargs['pk'],
        }
        return reverse('gestor:detail_cotizacion', kwargs=cotizacion_kwargs)

class ProductoAdd(CreateView):
    template_name = 'gestor/producto/ProductoAdd.html'
    model = ProductoCotizado
    form_class = ProductoAddForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        context['cotizacion'] = Cotizacion.objects.get(pk=self.kwargs['pk'])
        context['producto'] = Producto.objects.get(id=self.kwargs['id'])
        return context

    def form_valid(self, form):
        form.instance.cotizacion = Cotizacion.objects.get(pk=self.kwargs['pk'])
        form.instance.producto = Producto.objects.get(id=self.kwargs['id'])
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        cotizacion_kwargs = {
            'rfc': self.kwargs['rfc'],

templates/gestor/producto/ProductoAdd.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content%}
{% load widget_tweaks %}
<h4>Cotización: <a href="{% url 'gestor:detail_cotizacion'  empresa.rfc cotizacion.id %}">#{{cotizacion.id}}</a></h4>
<div class="container">
  <h5>Producto: <a href="{% url 'gestor:detail_producto' producto.id %}">#{{producto.id}}</a></h5>
  <h6>Nombre: {{producto.nombre}}</h6>
  <p>Tipo de producto: {{producto.tipo_producto}}</p>
  <p>Unidad de medida: {{producto.unidad_medida}}</p>
  <p>Clave: {{producto.clave}}</p>
</div>
<form method="post">{% csrf_token %}
  <div id="Calculadora">
    <div class="form-group row">
      <label for="{{form.margen_ganancia.id_for_label}}" class="col-sm-2 col-form-label">{{form.margen_ganancia.label_tag}}</label>
      <div class="input-group col-sm-10">
        {{form.margen_ganancia|attr:"v-model.number:margen"|attr:"class:form-control"}}
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.costo.id_for_label }}" class="col-sm-2 col-form-label">{{ form.costo.label_tag }}</label>
      <div class="input-group col-sm-10">
        {{ form.costo|attr:"v-model.number:costo"|attr:"class:form-control" }}
        <div class="input-group-append">
          <span class="input-group-text">%&#x25B2;${margen}</span>
          <span class="input-group-text">Precio:</span>
          <span class="input-group-text">${getPrecio(costo)}</span>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.cantidad.id_for_label }}" class="col-sm-2 col-form-label">{{ form.cantidad.label_tag }}</label>
      <div class="input-group col-sm-10">
        {{ form.cantidad|attr:"v-model.number:cantidad"|attr:"class:form-control"  }}
        <div class="input-group-append">
          <span class="input-group-text">${precio}</span>
          <span class="input-group-text">Importe:</span>
          <span class="input-group-text">${getImporte()}</span>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="{{ form.provedor.id_for_label }}" class="col-sm-2 col-form-label">{{ form.provedor.label_tag}}</label>
    <div id="BuscarProvedor">
      <div class="col-sm-10">
        <div class="input-group">
          <div class="input-group-prepend">
            <button class="btn btn-outline-primary" type="button" data-toggle="modal" data-target="#buscarProvedorModal">
              Buscar Provedor
            </button>
          </div>
          {{form.provedor|attr:"class:custom-select"|attr:"v-model:currentEmpresaRFC"}}
          </div>
        </div>
      <!-- Buscar Provedor Modal -->
      <div class="modal fade" id="buscarProvedorModal" tabindex="1" role="dialog" aria-labelledby="buscarProvedorModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5>Buscar Provedor</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-inline my-log-0">
                <input class="form-control mr-sm-2" type="text" placeholder="rfc, nombre"
                  v-model="search_term" aria-label="Buscar">
                <button class="btn btn-outline-success my-sm-0" v-on:click.prevent="getEmpresaList()">
                  Buscar
                </button>
              </div>
              <div class="my-1">
                <table class="table">
                  <thead class="thead-light">
                    <tr>
                      <th scope="col">RFC</th>
                      <th scope="col">Razón social</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="empresa in empresaList">
                      <th scope="col">
                        <a  href="#" v-on:click="getEmpresa(empresa.rfc)">${empresa.rfc}</a>
                      </th>
                      <th scope="col">${empresa.razon_social}</th>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="{{ form.descripcion.id_for_label }}" class="col-sm-2 col-form-label">
      {{form.descripcion.label_tag}}
    </label>
    <div class="col-sm-10">
      {{ form.descripcion|add_class:'form-control' }}
    </div>
  </div>
  {% if cotizacion.usuario == request.user %}
    <input type="submit" class="btn btn-lg btn-secondary my-2" value="Agregar producto">
  {% endif %}
</form>

{% endblock %}

{% block scripts %}
  {% load static %}
  <script src="{% static 'frontend/producto_add.js' %}"></script>
{% endblock %}

templates/gestor/producto/ProductoCotizadoUpdate.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content%}
{% load widget_tweaks %}
<h4>Cotización: <a href="{% url 'gestor:detail_cotizacion'  empresa.rfc cotizacion.id %}">#{{cotizacion.id}}</a></h4>
<div class="container">
  <h5>Producto: <a href="{% url 'gestor:detail_producto' producto.id %}">#{{producto.id}}</a></h5>
  <h6>Nombre: {{producto.nombre}}</h6>
  <p>Tipo de producto: {{producto.tipo_producto}}</p>
  <p>Unidad de medida: {{producto.unidad_medida}}</p>
  <p>Clave: {{producto.clave}}</p>
</div>
<h5>Producto Cotizado: #{{producto_cotizado.id}}</h5>
<div class="container">
  <p>Costo: ${{producto_cotizado.costo}}</p>
  <p>Margen de ganancia: %{{producto_cotizado.margen_ganancia}}</p>
  <p>Precio: ${{producto_cotizado.precio}}</p>
</div>
<form method="post">{% csrf_token %}
  <div id="Calculadora">
    <div class="form-group row">
        <label for="{{form.margen_ganancia.id_for_label}}" class="col-sm-2 col-form-label">{{form.margen_ganancia.label_tag}}</label>
        <div class="input-group col-sm-10">
          {{form.margen_ganancia|attr:"v-model.number:margen"|attr:"class:form-control"}}
        </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.costo.id_for_label }}" class="col-sm-2 col-form-label">{{ form.costo.label_tag }}</label>
      <div class="input-group col-sm-10">
        {{ form.costo|attr:"v-model.number:costo"|attr:"class:form-control" }}
        <div class="input-group-append">
          <span class="input-group-text">%&#x25B2;${margen}</span>
          <span class="input-group-text">Precio:</span>
          <span class="input-group-text">${getPrecio(costo)}</span>
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.cantidad.id_for_label }}" class="col-sm-2 col-form-label">{{ form.cantidad.label_tag }}</label>
      <div class="input-group col-sm-10">
        {{ form.cantidad|attr:"v-model.number:cantidad"|attr:"class:form-control" }}
        <div class="input-group-append">
          <span class="input-group-text">${precio}</span>
          <span class="input-group-text">Importe:</span>
          <span class="input-group-text">${getImporte()}</span>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="{{ form.provedor.id_for_label }}" class="col-sm-2 col-form-label">{{ form.provedor.label_tag}}</label>
    <div id="BuscarProvedor">
      <div class="input-group col-sm-10">
        <div class="input-group-prepend">
          <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#buscarProvedorModal">
            Buscar Provedor
          </button>
        </div>
        {{form.provedor|attr:"class:form-control"|attr:"v-model:currentEmpresaRFC"}}
      </div>
      <!-- Buscar Provedor Modal -->
      <div class="modal fade" id="buscarProvedorModal" tabindex="1" role="dialog" aria-labelledby="buscarProvedorModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5>Buscar Provedor</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-inline my-log-0">
                <input class="form-control mr-sm-2" type="text" placeholder="rfc, nombre"
                  v-model="search_term" aria-label="Buscar">
                <button class="btn btn-outline-success my-sm-0" v-on:click.prevent="getEmpresaList()">
                  Buscar
                </button>
              </div>
              <div class="my-2">
                <table class="table">
                  <thead class="thead-light">
                    <tr>
                      <th scope="col">RFC</th>
                      <th scope="col">Razón social</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="empresa in empresaList">
                      <th scope="col">
                        <a  href="#" v-on:click="getEmpresa(empresa.rfc)">${empresa.rfc}</a>
                      </th>
                      <th scope="col">${empresa.razon_social}</th>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="{{ form.descripcion.id_for_label }}" class="col-sm-2 col-form-label">
      {{form.descripcion.label_tag}}
    </label>
    <div class="col-sm-10">
      {{ form.descripcion|add_class:'form-control' }}
    </div>
  </div>
  {% if cotizacion.usuario == request.user %}
    <input type="submit" class="btn btn-lg btn-secondary my-2" value="Guardar cambios">
  {% endif %}
</form>
{% endblock %}

{% block scripts %}
  {% load static %}
  <script src="{% static 'frontend/producto_add.js' %}"></script>
{% endblock %}

templates/gestor/producto/ProductoDetail.html
{% extends "gestor/base.html" %}

{% block content %}

{% endblock %}